# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 790ac0fbc96d136c104e4d9e4f9b5b8255cbd282e4a36b839e00aed02f98f7bd6d132c2ac0c8bef63c7ea292a694c5dcfc2dec3067a5c011b4cae5a07c4032da

test:
  secret_key_base: afc38b947dcdf5d6f326a6798bb28141d4d3bdc3030d25e996f00d40aec06d099a34ce4b73d85235eca977c54eac8d2dd9de570a747c85912b33181e2593fa96

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
